services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo_db
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: demo_pass
    ports:
      - "8080:8080"
  
  frontend:
    build: /Users/marie.collinge/dev_folder/ESA_FE/ticketing-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080
    ports:
      - "5173:5173"
      
volumes:
  db-data: